.gitignore, user-service/.env, user-service/common/logger.js, user-service/controller/login-controller.js, user-service/controller/user-controller.js, user-service/index.js, user-service/model/login-orm.js, user-service/model/repository.js, user-service/model/user-model.js, user-service/model/user-orm.js, user-service/routes/login-routes.js, user-service/routes/user-routes.js
1. Refactored routes
2. Removed password field from user model , only hashed passwords will be stored
3. Added ./common/logger.js file for logging constants 
4. Added login feature
- Added login route, controller and orm
- Added loginUser function
- Added function to check password when logging in
-  Added JWT token generation when logging in
=> Login feature and JWT token generation

user-service/controller/user-controller.js, user-service/model/repository.js, user-service/model/user-orm.js, user-service/routes/user-routes.js
1. Created a new route for user to change password.
2. Added function to change password in controller layer.
=> Add change password function

user-service/controller/user-controller.js, user-service/model/repository.js, user-service/model/user-orm.js, user-service/routes/user-routes.js
1. Create a new route for user to delete their account
2. In the controller layer, implemented the function to delete user.
3. Add check for if current password and new password are the same for changePassword function.
=> Add delete account feature for users to delete their account

question-service/index.js, question-service/model/question-model.js, question-service/package-lock.json, question-service/package.json, question-service/route/question-route.js
Designed Question model plus made the files for the controller and routes
=> Question model

matching-service/package-lock.json, matching-service/package.json, package-lock.json
* Removed redundant dependencies in `matching-service/package.json`
* Not sure why cors wasn't added previously but I just added it to `package.json`
* Removed stray package.json in top-level directory, previously committed and added in another PR.
=> Corrected package.json packages and removed stray package.json

README.md, docker-compose.yml, matching-service/common/constants.js, matching-service/controllers/matchController.js, matching-service/index.js, matching-service/models/interview.js, matching-service/package-lock.json, matching-service/package.json, question-service/controller/question-controller.js, question-service/dockerfile, question-service/index.js, question-service/model/question-model.js, question-service/route/question-route.js, user-service/index.js
* Added axios call to question service from matching service
* Question will be stored under the interview document once it is created
* Updated ports for user/matching/question services
* Updated root README
* Add dockerfile for question service
* Updated docker-compose file with question service
* Tested docker-compose containers
* Minor refactors
=> Link Matching to Question Service + Docker updates

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/HomePage.js, frontend/src/components/InterviewPage.js, frontend/src/components/SearchPage.js, frontend/src/services/matchingService.js
Search Page
- 30 second timer shown while finding match
- Users will be redirected back to home if no match is found within 30 seconds
- Users will be redirected back to home if they cancel find match. A window will pop up to ask them to confirm if they want to cancel finding match when clicking the cancel find match button. Upon confirmation in the window popup, users will be redirected back to home
- Users will be redirected to interview page if a successful match is found
Interview Page
- Question of type difficulty that was selected by the matched users will be shown on the screen
- Users will be able to end the interview by clicking the end interview button. A window popup will then be shown asking the users to confirm again whether they want to end the interview. Users will then be …
=> Add search page and interview page functionality in frontend

history-service/controllers/historyController.js, history-service/index.js, history-service/models/history.js, history-service/package-lock.json, history-service/package.json, history-service/routes/historyRoutes.js
- Created schema for history-service
- API to create history
- API to get history
- Tests will be subsequently added in future PRs
=> Backend for history-service

question-service/.dockerignore
=> Add dockerignore file to question service

chat-service/.dockerignore, chat-service/dockerfile, docker-compose.backend.yml, docker-compose.yml
Added docker file to chat-service and updated docker compose file
=> Add docker files for Chat service

.github/workflows/chat-service.yml, .github/workflows/history-service.yml, .github/workflows/user-service.yml, chat-service/index.js, chat-service/package-lock.json, chat-service/package.json, chat-service/test/test.js, chat-service/test/testData.js, frontend/src/components/Chat.js, frontend/src/components/InterviewPage.js
Changes made:
1. Followed collab-service naming convention of socket routes
2. Added tests for chat-service
3. Added CI for chat-service
=> Add Chat service tests and CI

frontend/src/components/NavBar.js, frontend/src/components/SearchPage.js, frontend/src/components/SettingsPage.js
- Centre left tab messages on settings page
- Remove navbar from search page
- Change options dropdown in navbar to logout only
=> Edits to frontend

frontend/src/components/InterviewPage.js, frontend/src/services/matchingService.js, matching-service/controllers/matchController.js, matching-service/package-lock.json, matching-service/routes/matchRoutes.js
- Add find interview by username API
- Change route names in frontend due to naming changes in the routes for backend
=> Add find interview by username, change route names

docs/sequence-diagrams/chat-service.puml, docs/sequence-diagrams/collab-service.puml, docs/sequence-diagrams/history-service.puml, docs/sequence-diagrams/matching-service.puml, docs/sequence-diagrams/question-service.puml, docs/sequence-diagrams/user-service.puml
https://towardsdatascience.com/drawing-a-uml-diagram-in-the-vs-code-53c2e67deffe
Install vscode extension, that's all.
Refer to google docs for actual diagrams.
=> add all 6 sequence diagrams

.github/workflows/collaboration-service.yml, collaboration-service/.dockerignore, collaboration-service/dockerfile, collaboration-service/index.js, collaboration-service/package-lock.json, collaboration-service/package.json, collaboration-service/test/test.js, collaboration-service/test/testData.js, docker-compose.backend.yml, docker-compose.yml, frontend/src/components/CodeEditor.js, frontend/src/components/InterviewPage.js
Refactored naming of socket connections.
Removed excess console logs.
Added npm test (Only had one in mind since I did not make many logs/responses for connections). If there's any more can suggest and I'll make the required changes.
Dockerized Collab and tested functionality.
=> Dockerize collab

matching-service/models/interview.js
Previously was defaul instead of default for createdAt field.
=> Fix missing default field in interview model

chat-service/index.js, chat-service/test/test.js, frontend/src/components/HistoryPage.js, frontend/src/components/InterviewPage.js, frontend/src/components/SettingsPage.js, frontend/src/index.css
Chat-Service
- Added leave message
Frontend
- Minor changes to UI (Added shadows to make things look better)
=> Chat leave message and UI improvements

docker-compose.yml, frontend/src/components/InterviewPage.js, frontend/src/components/SearchPage.js, frontend/src/services/userService.js, user-service/controller/user-controller.js, user-service/routes/user-routes.js, user-service/test/test.js
User-service
- Minor change for routes from underscore( _ ) to hyphen (-)
- Minor changes to status codes
Frontend
- Minor changes to Interview Page (Include question difficulty and usernames in header)
Docker-file
- Removed env variables
=> Minor changes

frontend/src/components/HistoryPage.js, frontend/src/components/HomePage.js, frontend/src/components/LoginPage.js, frontend/src/components/SettingsPage.js, frontend/src/components/SignupPage.js, frontend/src/services/historyService.js
Delete account added enhancements
- User history will be deleted
- If user is in an interview, interview will be deleted
=> Delete history when user deletes account

docs/sequence-diagrams/user-service-change-password.puml, docs/sequence-diagrams/user-service-delete-account.puml, docs/sequence-diagrams/user-service.puml
=> Add UML diagrams for user-service
